org: osmansheikh
app: textrecon
service: textrecon

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: "20201221"
  timeout: 300
  environment:
    bucketName: ${self:custom.bucketName}
    imageUploadBucket: ${self:custom.imageUploadBucket}
    # replace these env variables with your twilio account values
    TWILIO_ACCOUNT_SID:
    TWILIO_AUTH_TOKEN:
    TWILIO_PHONE_NUMBER:
    GOOGLE_AUTH_TOKEN:
  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:*"
      Resource: "*"

functions:
  checkLink:
    handler: handler.checkLink
    layers:
      - arn:aws:lambda:us-east-1:764866452798:layer:chrome-aws-lambda:24
    events:
      - http:
          path: api/checkLink
          method: post

plugins:
  - serverless-webpack

custom:
  imageUploadBucket: textrecon-image-bucket-sws
  bucketName: textrecon-bucket

resources:
  Resources:
    imageUploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.imageUploadBucket}
        AccessControl: PublicRead
